name: Show Vars

on:
  #push:
  #  branches: [ master ]
  #  paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md]
  pull_request:
    branches: [ master ]
    paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md]
  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  
jobs:
  build_and_test:
    runs-on: [self-hosted, connect_to_jenkins_dispatcher]

    steps:
      - name: show vars
        run: |
          echo ${{ toJson(github) }}
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.workflow_dispatch.user.login: ${{ github.event.workflow_dispatch.user.login }}"
          echo "github.event.pull_request.user.login: ${{ github.event.pull_request.user.login }}"
          echo "github.event.pull_request.author.email: ${{ github.event.pull_request.author.email }}"
          echo "github.event.pull_request.user.login: ${{ github.event.pull_request.user.login }}"
          echo "github.event.pull_request.number: ${{ github.event.pull_request.number }}"
          echo "env.PR_NUMBER: ${{ env.PR_NUMBER }}"
          echo "----------------------------------"
          cat $GITHUB_EVENT_PATH
