name: Show Vars

on:
  #push:
  #  branches: [ master ]
  #  paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md]
  pull_request:
    branches: [ master ]
    paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md]
    #types:
    #  - created
  workflow_dispatch:

#env:
#  PR_NUMBER: ${{ github.event.pull_request.number }}
  
concurrency: 
  # pr时： Show Vars--refs/pull/5/merge--pull_request
  # 手动时: Show Vars--refs/heads/master--workflow_dispatch
  group: ${{ github.workflow }}--${{ github.ref }}--${{ github.event_name }}
  cancel-in-progress: true
  
jobs:
  build_and_test:
    runs-on: [self-hosted, connect_to_jenkins_dispatcher]

    steps:
      - name: show vars
        run: |
          echo "github.workflow--github.ref--github.event_name: ${{ github.workflow }}--${{ github.ref }}--${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.event.pull_request.number: ${{ github.event.pull_request.number }}"
          #echo "env.PR_NUMBER: ${{ env.PR_NUMBER }}"
          echo ${{ toJson(github) }}
          echo "sleep begin."
          sleep 10m
          echo "sleep end.
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.workflow_dispatch.user.login: ${{ github.event.workflow_dispatch.user.login }}"
          echo "github.event.pull_request.user.login: ${{ github.event.pull_request.user.login }}"
          echo "github.event.pull_request.author.email: ${{ github.event.pull_request.author.email }}"
          echo "github.event.pull_request.user.login: ${{ github.event.pull_request.user.login }}"
          echo "----------------------------------"
          #cat $GITHUB_EVENT_PATH
