name: PPL<x86 windows 64> Build && Quick Test

on:
  #push:
  #  branches: [ master ]
  #  paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md]
  pull_request:
    branches: [ master ]
    paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: [self-hosted, win64]

    steps:
      - name: Create Checkout Directory
        run: |
          #echo "Create Checkout Directory: ${{ github.run_id }}."
          #if ( Test-Path ${{ github.run_id }} ) { Remove-Item ${{ github.run_id }} -Recurse -Force}
          #mkdir ${{ github.run_id }}
          cd ../../ ; ./mk_src_dir.ps1 ${{ github.run_id }}
      #- name: Checkout
      #  uses: actions/checkout@v2
      #  with:
      #    path: ${{ github.run_id }}

      - name: Build
        run: |
          cd ../../ ; ./build_pplnn.ps1 ${{ github.run_id }} x86_64
          
      - name: Test
        run: |
          cd ../../ ; ./test_pplnn.ps1 ${{ github.run_id }} x86_64

      - name: clean
        if: ${{ always() }}
        run: |
          cd ../../ && ./clean_pplnn.ps1 ${{ github.run_id }} x86_64
          echo "clean up."
